name = "aether"
name_pretty = "Aether Menu"
global_search = false
keywords = [ "aether", "menu" ]
fixed_order = false
history = false
history_when_empty = false


[[entries]]
text = "Audio"
icon = "audio-speakers-symbolic"
actions = { "run" = "kitty --class wiremix wiremix" }
keywords = [ "audio", "wiremix" ]

[[entries]]
text = "Bluetooth"
icon = "network-bluetooth-symbolic"
actions = { "run" = "kitty --class bluetui bluetui" }
keywords = [ "bluetooth", "bluetui" ]

[[entries]]
text = "Idle"
async = """echo "Idle Inhibiton: $(/etc/aether/power/scripts/inhibition-status.sh)" """
icon = "stopwatch-symbolic"
actions = { "run" = "/etc/aether/power/scripts/inhibition-toggle.sh" }
keywords = [ "idle", "inhibition" ]

[[entries]]
text = "Power"
icon = "system-shutdown-symbolic"
submenu = "power"
keywords = [ "power", "reboot", "restart", "sleep", "suspend", "hibernate", "sleep", "logout", "shutdown" ]

[[entries]]
text = "Performance"
icon = "power-profile-balanced-symbolic"
submenu = "performance"
keywords = [ "performance" ]

[[entries]]
text = "Screenshot"
icon = "camera-photo-symbolic"
actions = { "run" = "/etc/aether/screen-capture/scripts/screenshot.sh" }
keywords = [ "screenshot", "screen", "capture" ]

[[entries]]
text = "Record Screen"
actions = { "run" = "kooha" }
icon = "camera-video-symbolic"
keywords = [ "record", "video", "capture", "screen" ]

[[entries]]
text = "Wifi"
icon = "network-wireless-connected-100-symbolic"
actions = { "run" = "kitty --class impala impala" }
keywords = [ "network", "wifi", "wi-fi", "wireless", "impala" ]

[[entries]]
text = "Garbage Collect"
icon = "user-trash-symbolic"
actions = { "run" = "/etc/aether/storage/scripts/garbage-collect.sh" }
keywords = [ "garbage", "collect", "store" ]

[[entries]]
text = "Process Monitor"
icon = "cpu-symbolic"
actions = { "run" = "kitty --class btop btop" }
keywords = [ "process", "task", "monitor", "manager" ]

[[entries]]
text = "Color Picker"
icon = "color-select-symbolic"
actions = { "run" = "hyprpicker -a" }
keywords = [ "color", "picker" ]
