name = "performance"
name_pretty = "Performance"
global_search = false
keywords = [ "performance" ]
fixed_order = true
history = false
history_when_empty = false
parent = "aether"

[[entries]]
text = "Auto"
actions = { "run" = "sudo auto-cpufreq --force reset", "test-action" = "mkdir ~/ttttt" }
icon = "edit-undo-symbolic"

[[entries]]
text = "Power Saver"
action = "sudo auto-cpufreq --force powersave"
icon = "battery-profile-powersave-symbolic"

[[entries]]
text = "Performance"
action = "sudo auto-cpufreq --force performance"
icon = "battery-profile-performance-symbolic"
