name = "power"
name_pretty = "Power"
global_search = false
keywords = [ "power" ]
fixed_order = true
history = false
history_when_empty = false

[[entries]]
text = "Shutdown"
actions = { "run" = "systemctl poweroff" }
icon = "system-shutdown-symbolic"
keywords = [ "shutdown", "power", "poweroff", "off" ]

[[entries]]
text = "Reboot"
actions = { "run" = "systemctl reboot" }
icon = "system-reboot-symbolic"
keywords = [ "reboot", "restart" ]

[[entries]]
text = "Suspend"
actions = { "run" = "systemctl suspend" }
icon = "system-suspend-symbolic"
keywords = [ "suspend", "sleep" ]

[[entries]]
text = "Hibernate"
actions = { "run" = "systemctl hibernate" }
icon = "system-hibernate-symbolic"

[[entries]]
text = "Logout"
actions = { "run" = "hyprctl dispatch exit" }
icon = "system-log-out-symbolic"

[[entries]]
text = "Lock Screen"
actions = { "run" = "loginctl lock-session" }
icon = "system-lock-screen-symbolic"

